### ISSUE TITLE
audio not right on one recording

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#1]
Peter, first, let me say how grateful i am that you are doing this, I really think you should charge something for your the software, your effort is worth it!

Now to my issue...I have been using it pretty regularly (first v.95, then the current version) and have run across one issue.  On one of my recordings (from antenna), the audio sounds very "tin canny"?? you can understand what is being said but it sounds bad. I am experiencing this on no other recording.  If you want to reach out privately, i will share the recording with you for testing, also, this is the basic info on the file, if it helps.

please let me know how i can help you fix this.

One additional note:  Not sure if it matters, but This is one of the few recordings i "cut" out commercials from.  i marked the commercials, then used the "lossless" transcoding feature to rewrite the recording...I don't know if that was part of the issue or not.

![2020-03-26 08_37_35-Remote Desktop](https://user-images.githubusercontent.com/25204879/77664680-f6fe0500-6f54-11ea-8708-e9ca60bb3e41.png)

**Comment by bennettpeter** [comment]
Have you tried different audio settings? In leanfront Settings you can select Audio options Mediacodec, FFMpeg or Auto. In Android Settings you can enable or disable Surround Sound. Do any of these changes make a difference?

Does the file play OK with other players, such as VLC or mythfrontend?

**Comment by tonyguadagno** [comment]
I know for sure it plays ok on the mythfrontend....i am not sure about anything else.  i will check.  also, i will check audio settings.

**Comment by tonyguadagno** [comment]
sorry, i forgot to mention as well, that i am using leanfront on an firestick 4k

**Comment by tonyguadagno** [comment]
hi, i just opened it up with vlc and it played as expected, audio sounds good.

**Comment by tonyguadagno** [comment]
peter, i just checked out the leanfront audio settings.  i was set to auto, so i tried both Mediacodec and FFMpeg.  both produced the same results, same bad audio.

fyi

**Comment by bennettpeter** [comment]
I got the sample file, and I confirm that the audio is corrupted. Exoplayer seems to have trouble demuxing the audio in the file.

The following command fixes the file without re-encoding. It takes only seconds to run:

`ffmpeg -i sample.mpg -acodec copy -vcodec copy -scodec copy -f mpegts repaired_sample.mpg
`

As a workaround, you could run that against your file and then overwrite the original file with the repaired file.

**Comment by tonyguadagno** [comment]
Peter, so do you mean corrupt as in not normal?  In other words, it not that it is an unexpected audio type, its that it is not encoded properly?

Tony

**Comment by bennettpeter** [comment]
When I said "corrupt", I mean that I hear the audio distorted, the same as you do. I don't know the cause, likely something in the lossless transcoding is causing this. Can you confirm that only files that have been through lossless transcoding have this problem?

**Comment by tonyguadagno** [comment]
Peter, yes, I just checked….all the recordings that I cut commercials out of (and then ran through lossless transcoding) are this way…..ug…why?  and why does the myth frontend (and vlc) not have any issue with it?

Tony

**Comment by bennettpeter** [comment]
This involves the internals of exoplayer. It will take some time to sort out. In the meantime, I suggest running the ffmpeg command shown above on the transcoded recordings.

**Comment by tonyguadagno** [comment]
Peter, sure, thanks for looking at it!

Tony

**Comment by bennettpeter** [comment]
There are issues with files processed by mythtv transcoding and also other programs, for example ProjectX. I will not be looking into this further, and I recommend running files through ffmpeg or mkvmerge after using these tools to make them compatible with leanfront (see "Problems" in the documentation).
