### ISSUE TITLE
Fails to run on second gen FireTV (pendant-style)

### ISSUE THREAD

**Issue by richbx** [bennettpeter/android-MythTV-Leanfront#10]
I installed leanfront-v0-239-g7770891 on a second gen FireTV (pendant, not stick).  It appears to crash right away when run.  The screen blanks and then it dumps right back to the home screen.  The second gen FireTV is android 5.1.1 with API level 22.  The official Mythtv frontend and Kodi both run on the same device.  I have not tried any older leanfront releases.

The attached log was captured with 'adb logcat > log', launch leanfront, then ctrl-c out of adb.  Hope this is right.  Let me know if I can get any other info.

[leanfront-v0-239-firetv-gen2.log.gz](https://github.com/bennettpeter/android-MythTV-Leanfront/files/5721417/leanfront-v0-239-firetv-gen2.log.gz)

**Comment by bennettpeter** [comment]
I fixed the problem with fire stick release 2, same conditions you reported. Hopefully it will also resolve your problem. Try the new version v0-240-g97a6708.

**Comment by bennettpeter** [comment]
If it does not work, try uninstalling and re-installing. i don't know if that would be necessary. It may have done a partial setup of the database and failed in a bad state.

**Comment by richbx** [comment]
Yes, 240 fixes the problem.  I went ahead and uninstalled the previous version and installed 240 and it is running fine now.  I don't know if it was necessary to uninstall but I didn't have any settings or anything to lose so I went that route.  Thanks a lot, it looks great!
