### ISSUE TITLE
PGS subtitles not supported, regression?

### ISSUE THREAD

**Issue by faginbagin** [bennettpeter/android-MythTV-Leanfront#102]
Hit enter too soon!

I have been watching bluray rips with PGS subtitles without a problem for a long time. But then a couple of days ago, I could not turn them on. I would get a toast with the message:
Error: subtitle type application/x-media3-cues is not supported.

I suspect I hit this problem when amazon pushed out the latest leanfront version to my firetv 4k stick. It is now running what I believe is the version built after the August 6th commit: v0-516-g6a5394e-m1.4.0-1-g007aad1acd

I confirmed it's a regression by installing the latest apk I had from before you added support for Amazon's appstore, on a second firetv 4k stick:
20220802-leanfront-release-v0-365-ge5295c8.apk

Both sticks are running the same version of Fire OS: 6.7.0.5 (NS6705/5380)

I extracted a sample clip of about 120 Mb, 30+ seconds long that demonstrates the problem. Much to my surprise, when I played it in the latest version of leanfront, the subtitles worked! Turns out that ffmpeg change the default state of the subtitles from off to on. So I used mkvpropedit from mkvtoolnix to create a clip where the default is off.

There are now two clips in my google drive, here:
https://drive.google.com/drive/folders/1rR15WUvZ_k_dYUVEHlcVdVIcSW_B_73O?usp=sharing
pgs-on.mkv is the file I clipped from the bluray rip using mythffmepg
pgs-off.mkv is that file modified by mkvpropedit to change the default state of the subtitles from on to off.

I hope these clips are sufficient for you to debug the issue. But I'm happy to help in any way I can. For example, if you have older APKs, I could do some initial bisecting on my second firetv stick. Or if you want logs, I'd be happy to provided them.

**Comment by bennettpeter** [comment]
All of the old and current apk files are on the google drive, 
 https://drive.google.com/drive/u/3/folders/1LMf7dTK_fD_e1S3S2HgB1NEPsWI0MdyB
The apks since it went to the play store are in the "Android leanfront" directory. Earlier ones are in "Prior Versions" along with other stuff. Unfortunately installing one of these will require uninstalling first, and you will lose your settings and history.

The latest version, v0-516, has a new version of exoplayer. I suspect that may be the problem. In the newest apks, the part of the version number that starts with "-m" identifies the exoplayer version.

From the description it looks like you are saying if the subtitles are forced they work but if not forced they give an error when you select them.

**Comment by bennettpeter** [comment]
Most subtitles are  failing. There appears to be a bug in the android media call to check subtitle support. It is returning false for a type that is supported.

I have removed the check for support. Get the new version from the "Trial Versions" directory. If all is well I will release it net week.

On an amazon fire stick you will have to uninstall the store version to install this. On an android device you will not have to uninstall.

**Comment by jksj461** [comment]
leanfront-release-v0-517-g9f99ecc-m1.4.0-1-g007aad1acd
Does not resolve the issue for UK Freesat broadcasts.
The error remains as 
Unexpected Exception
then Unexpected run time error
When the subtitle track is selected.
If I install an earlier version how do you prevent it from automatically updating?

**Comment by bennettpeter** [comment]
If you uninstall and then install from an apk file it will not automatically update. To get back to the play store versions and automatic updates you will have to uninstall again and install from the store.

For the one that fails, did it work before? Please provide a sample that fails on 517.

**Comment by faginbagin** [comment]
@jksj461 what I have done while testing is to disable automatic updates in the appstore. Go to Settings -> Applications -> Appstore, the turn off Automatic Updates.

The trial version fixes the problem I first reported. I have also gone back and retested some other samples with the previous release, the current release and the trial version. @bennettpeter you asked if forced subtitles work. The MKV container has two flags that apply to subtitles, default and forced. The forced flag is off on all my MKV test samples. A couple has the default flag on, which gave me the means to work around the problem in the current release.

Here are my notes. In general the format per text case is:
result: sample description: subtitle codec & default/forced flag if relevant
&  optional extra notes
Hope they make sense!

Version: x-20240714_leanfront-release-v0-507-g9ff75d3-m1.2.1-2-gc3114cd837.apk
*** DVD & blu ray rips ***
supported: 3rd Rock from the Sun/s01e01 (transcode).mkv: S_TEXT/UTF8, default=yes, forced=no
&  starts on, can turn off & on
supported: As Time Goes By/s01e01.mp4: tx3g
supported: pgs-off: S_HDMV/PGS, default=no, forced=no
&  always takes longer to start playback than pgs-on.mkv
supported: pgs-on: S_HDMV/PGS, default=yes, forced=no
&  starts on, can turn off & on
*** recordings ***
only CC1 supported: Bones,2202_20140926000000.mpg: CC1 EIA-608,ATSC EIA-708

Version: x-20240811-leanfront-release-v0-516-g6a5394e-m1.4.0-1-g007aad1acd.apk
*** DVD & blu ray rips ***
workaround: 3rd Rock from the Sun/s01e01 (transcode).mkv; S_TEXT/UTF8, default=yes, forced=no
& subtitles start out displayed and can be turned off, but can't be turned back on
not supported: As Time Goes By/s01e01.mp4: tx3g
not supported: pgs-off: S_HDMV/PGS, default=no, forced=no
& always takes longer to start playback than pgs-on.mkv
workaround: pgs-on: S_HDMV/PGS, default=yes, forced=no
& subtitles start out displayed and can be turned off, but can't be turned back on
*** recordings ***
only CC1 supported: Bones,2202_20140926000000.mpg: CC1 EIA-608,ATSC EIA-708

Version: leanfront-release-v0-517-g9f99ecc-m1.4.0-1-g007aad1acd.apk
*** DVD & blu ray rips ***
SUPPORTED!: 3rd Rock from the Sun/s01e01 (transcode).mkv; S_TEXT/UTF8, default=yes, forced=no
&  subtitles start out displayed and can be turned off, but can't be turned back on
SUPPORTED!: As Time Goes By/s01e01.mp4: tx3g
SUPPORTED!: pgs-off: S_HDMV/PGS, default=no, forced=no
&  always takes longer to start playback than pgs-on.mkv
SUPPORTED!: pgs-on: S_HDMV/PGS, default=yes, forced=no
&  subtitles start out displayed and can be turned off, but can't be turned back on
*** recordings ***
only CC1 supported: Bones,2202_20140926000000.mpg: CC1 EIA-608,ATSC EIA-708

**Comment by bennettpeter** [comment]
@faginbagin According to your response, with v0-517 and pgs-on you can turn subtitles off and not on again. Can you confirm this? My testing with the files you supplied shows I can turn them off and turn them on again.

Same question with 3rd Rock from the Sun and v0-517, are you sure you cannot turn them on again.

I removed the check for Supported type, so you should never see the "subtitle type XXXX is not supported", if it is really not supported you will see an exception error.

**Comment by bennettpeter** [comment]
@jksj461 I have a sample from British TV and I can see the problem.

It is a bit weird. It says you have dvbsubs and they are supported, then it says they are not supported you need to use application/x-media3-cues, then it says that application/x-media3-cues are not supported.

It is time to revert the exoplayer version to the prior one that was working.

**Comment by faginbagin** [comment]
My apologies, I probably copied and pasted and didn't remove the comments about not being able to turn them back on again. I could definitely turn the back on with 517.

**Comment by bennettpeter** [comment]
I have reverted the exoplayer version to 1.2.1. Other than that this is the same as v0-516. It is in 
https://drive.google.com/drive/u/3/folders/1LMf7dTK_fD_e1S3S2HgB1NEPsWI0MdyB in "Trial Versions". Note that this is the same high level version v0-517 as the previous Trial version. I have added a date in front to distinguish them.

Try this. It should fix the British subtitle problem as well as the PGS problem.

**20240815-leanfront-release-v0-517-g9d9a103-m1.2.1-2-gc3114cd837.apk**

If all is OK I will release this next week.

**Comment by faginbagin** [comment]
20240815-leanfront-release-v0-517-g9d9a103-m1.2.1-2-gc3114cd837.apk works for me, as it did before the exoplayer change and as it did with leanfront-release-v0-517-g9f99ecc-m1.4.0-1-g007aad1acd.apk

**Comment by jksj461** [comment]
20240815-leanfront-release-v0-517-g9d9a103-m1.2.1-2-gc3114cd837 works fine - many thanks.
Trested on UK Freeview & Freesat streams

**Comment by bennettpeter** [comment]
version 20240817-leanfront-release-v0-517-g9d9a103-m1.2.1-2-gc3114cd837 has been released in the Google and Amazon stores. If you had uninstalled to install it manually you will need to install from the Store again so you can get automatic updates in future.
