### ISSUE TITLE
Expand search to program description 

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#103]
Would it be possible to either a) expand search to include program descriptions or b) make the expanded search a setting option.

For example, searching "Thanksgiving" only brings up shows with that word in the title or episode title but it misses, say, a sitcom episode with "Bob tells his wife he'll make Thanksgiving dinner, only to discover he's the biggest turkey."

**Comment by bennettpeter** [comment]
If you go to the web app on backend:6544, and in the program guide, perform "Full Search" (magnifying glass with a plus sign inside), I think it does what you want.

Please check if that satisfies what you need.

 I could add that to the search, but in some cases it may be too much. I could also make that another row on the search result or add a setting to select the type of search desired.

**Comment by dheian** [comment]
Thanks. I was aware of that on the web frontend, just thinking of the easy family access on the app as they sit in front of the TV and suddenly get an idea. One option besides a permanent setting: it shows the recording and guide results and then there's a button that says

**Comment by dheian** [comment]
Sorry, hit Close by mistake. 😂

**Comment by bennettpeter** [comment]
What I actually was trying to ask is.:

Does a search that returns the result you get when you run "Full Search" on web app give you the results you are looking for in leanfront? i.e. if I implement the "Full Search" in leanfront would that satisfy?

**Comment by dheian** [comment]
Sorry I missed that. Not enough sleep last night. Did a full search using my example of "Thanksgiving" and rec'd a bunch of show results where the word was just in the episode description. So implementing that in Leanfront would satisfy.

**Comment by bennettpeter** [comment]
This is implemented in v0-531-gff25683. An extra row of results from the search.
