### ISSUE TITLE
Recording due to search rule doesn't show description 

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#104]
If I have a show that is recording due to a search rule e.g. People, Keyword, Title, Custom, clicking on a Will Record show in the guide will only show the rule that triggered the recording and not the description of the show.

For example, I have a People Search for David Letterman to catch his appearances on talk shows and old variety shows. A Carson episode is recording today. When I click on it in the program guide, it just says "David Letterman (People Search)" but it would be great if it also gave the description of the episode. Thanks.

**Comment by bennettpeter** [comment]
Actually, that info seems to be already available. If you select the paperclip icon (normally used for creating an override rule), you can see the description of the episode. After reading it, use the BACK key to exit without creating an override.

Let me know if this works for you.

**Comment by dheian** [comment]
Hadn't noticed that. Thanks for pointing it out.
