### ISSUE TITLE
MPEG2 file will not play correctly on leanfront after lossless transcode to remove commercials

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#105]
[mythtranscode-lossless (copy).sh.txt](https://github.com/user-attachments/files/17966264/mythtranscode-lossless.copy.sh.txt)

The attached file is a User Job in myhtv that I use to remove the commercials that the cutlist reflects and stores the file in it's original location and updates the database with the new file size and then rebuilds the seektable with mythcommflag.

This works fine if mythfrontend is used to playback the file. However, leanfront can't play it correctly. Missing audio and almost a slow motion video. I've tested this on FireTV 4k Max and Sony TV with Google TV

If I take the file and copy it to the VIdeo Storage group and do a scanvideo, it still plays the same in Leanfront. I did this to see if something in the database was causing it.

**Comment by bennettpeter** [comment]
Does it play with VLC?

I have seen this problem before with files that were processed with various tools. I recommend running it  through mkvmerge, which converts it to an mkv file. You can name the resulting file the same as the original file and replace it on disk and that should play fine with mythfrontend as well as leanfront. This process may lose subtitles.

You will need to delete the seektable if you convert it to an mkv file. You can do that with mythutil.

Note that you cannot rebuild the seektable on an mkv file. mkv files have their own built-in seek table, so they seek faster in leanfront than ts files do. leanfront does not use the mythtv seek table.

If you don't want to have it converted to mkv you could try running it through ffmpeg, using copy for each codec and outputting to a ts file. This may avoid losing the subtitles.

**Comment by jfabernathy** [comment]
It plays fine with vlc and kodi. I'll play around with mkvmerge.  This is more or less a learning project. 99% of the time I just record a show and skip the commercials using the remote since Leanfront does that quickly. On shows that I want to save I edit all the commercials out and use my version of the old sendTVtoNAS script from mythtv forum.  I've found that none of the builtin UserJob transcode jobs in mythtv work at all so I was just experimenting with could I make one that would just clear out the flagged commercials and leave it on mythtv so all the frontends could play it without difficulty. I have one that transcodes to mp4 and leaves it on mythtv, but not ideal for quality, but Anroid tablets can play it fine.

**Comment by jfabernathy** [comment]
After trying to figure out mkvmerge which will not read a .ts file directly, I looked at my choices. 

I have a User Job that will convert the original recording to .mp4 and which mythfrontend and Leanfront can play. But Android tablets can also play it. I also have a User job that assumes you've manually edited out all the commercials and created a cutlist, and converts that to .mp4. 

The downside to the .mp4 conversion is about 20 minutes of time per recording and a small loss of quality. Not a bad tradeoff.

I have workable alternatives. but since Leanfront can play the original .TS file it should play be lossless .ts converted file that just have the commercials cut out. I'm betting that mythtranscode doing lossless has issues.  Most uses of mythtranscode I've seen are just the frontend that strips the commercials before using handbrake to convert to .mp4 which seems to not care.

No big deal. I just wanted to document.

**Comment by bennettpeter** [comment]
> After trying to figure out mkvmerge which will not read a .ts file directly, I looked at my choices.

mkvmerge will read a ts file directly and output an mkv file. I do that  regularly. It can read most video file types, but only write mkv files.

mkvmerge -o "$newfile" "$oldfile"

**Comment by jfabernathy** [comment]
Thanks for the hint.  I took a recording and manually edited the cutlist to eliminate the commercials. I then used my lossless script I attached to this issue. The resultant file played fine in mythfrontend but I had to manaully clear the cutlist since I didn't do that in the script.  Then I ran `mkvmerge -o leanfront-test.mkv 30503_20241130160000.ts`.
I copied that mkv file to my video storage group and then did `mythutil --scanvideos` mythfrontend still played it right as a video and not a TV recording.  I went over to a FireTV  and it now played leanfront-test.mkv correctly just like mythfrontend.

So the test that remains is can I move leanfront-test.mkv back to the Default Storage group and rename it 30503_20241130160000.mkv and update mythconverg to set the basename to the new name and update the file size like I do when I update in place to a mp4 file.  I know mythfrontend can handle .ts and .mp4, but not sure about .mkv.  I'll test tomorrow and see what happens.

**Comment by jfabernathy** [comment]
I modified my lossless user job script and attached.
[mythtranscode-lossless.sh.tar.gz](https://github.com/user-attachments/files/17978558/mythtranscode-lossless.sh.tar.gz)
It works in mythfrontend , but I get a rendering error in leanfront. mythfrontend handled the new basename in mythconverg being a .mkv file fine, but leanfront didn't like something.  

I can setup for adb debugging if you want, but first wanted to see if you spot an obvious error with my script that would affect leanfront and not mythfrontend.

**Comment by jfabernathy** [comment]
I found one thing that fixes the .mkv file for Leanfront . I added in the lines:
```
$INSTALLPREFIX/mythutil --chanid "$CHANLID" --starttime "$STRTTIMUTC" --clearcutlist >> $LOGFILE
$INSTALLPREFIX/mythutil --chanid "$CHANLID" --starttime "$STRTTIMUTC" --clearbookmarks >> $LOGFILE
```
However, now in mythfrontend it will not do the normal skip/jump as it should and does in leanfront. I may need to add some more things to clear before running mkvmerge.

**Comment by bennettpeter** [comment]
If the cut list and comm skip list were from before a transcode they would no longer be valid. Perhaps leanfront is trying to skip a commercial or a cut and finding a value that is outside of the range of the video. If you turn off comm skipping in leanfront then does it play?

**Comment by jfabernathy** [comment]
> If the cut list and comm skip list were from before a transcode they would no longer be valid. Perhaps leanfront is trying to skip a commercial or a cut and finding a value that is outside of the range of the video. If you turn off comm skipping in leanfront then does it play?

So in my most recent post I noted that I fixed Leanfront by adding in clearing the cutlist, etc. Now I'm trying to fix mythfrontend skipping without screwing up Leanfront again.

**Comment by jfabernathy** [comment]
I can't find a lossless transcoding solution that works in both mythfrontend and leanfront. Since it's not that important to me, I'll not worry you about it anymore.
