### ISSUE TITLE
commercial skip

### ISSUE THREAD

**Issue by jseagull1** [bennettpeter/android-MythTV-Leanfront#11]
Hello, 
This isn't an issue, just a question. Does commercial skip work on leanfront? I haven't found it to work and wanted to be sure I'm not missing anything.

Thank you.
John

**Comment by bennettpeter** [comment]
The only way to skip commercials with leanfront is using back and forward skip (left / right arrow) when you get to a commercial. leanfront does not use MythTV commercial detection.
