### ISSUE TITLE
Letterboxing not black

### ISSUE THREAD

**Issue by coliss86** [bennettpeter/android-MythTV-Leanfront#12]
Hi, 

thanks for your work !
When playing a video with a different aspect ratio of the ratio of the TV, the color of the letterboxing are not black but grey.
I tested the same video with different player (kodi, vlc) and they are black.

I'm using a Nvidia Shield 4K HDR.

**Comment by bennettpeter** [comment]
Is that a problem?

The player is exoplayer and the color was determined by that. I will take a look and see if it can be changed. Perhaps it could be selected with a setting.

**Comment by coliss86** [comment]
I rather prefer the black color.

Thanks for your help :muscle:

**Comment by bennettpeter** [comment]
Fixed - select black letterbox matte in settings -> Playback

**Comment by coliss86** [comment]
Perfect ! I just tried with the emulator.

Next task : create an apk for the TV (was hard to run in emulator, I'll do a PR in a few days)

**Comment by bennettpeter** [comment]
I did post an apk (release version) on the site https://dl.orangedox.com/pCBmBm . Does that fail on your TV?

**Comment by coliss86** [comment]
I may misunderstood : the version on your site `gfa3a385` does not seem to correspond to any commit. Does it include this fix ?

**Comment by bennettpeter** [comment]
If you look at commits by clicking where it says "539 commits" you can see a list of commits. You can see  fa3a385  "Add a setting for Black Letterbox matte"  there. That is the commit mentioned above. Yes it has this fix!

**Comment by coliss86** [comment]
Thanks, I was not seeing it because there a `g` at the beginning of the revision of the apk

**Comment by coliss86** [comment]
Perfect, tested successfully on my TV
