### ISSUE TITLE
small percentage of recordings have no length displayed and I cannot ff or rew on them

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#14]
Hi,  I have noticed this on 2 of my recordings.  the recordings seem to play fine, however, there is no length displayed at the bottom right.  Also ff and rew do not work. 

i was on leanfront-release-v0-261-g92ab8a3.apk but just upgraded to leanfront-release-v0-284-gde137ef.apk and the recordings are behaving the same.

i can provide samples if you are interested.

thanks

**Comment by bennettpeter** [comment]
Go to Settings, Tweaks and increase the value of **TS Search Packets** .

**Comment by tonyguadagno** [comment]
ok, i will try that and let you know.
thanks

**Comment by tonyguadagno** [comment]
hi, i tried 4000 and 6000 and had the same behavior....should i be going higher?

**Comment by bennettpeter** [comment]
If it still does not work at 100,000 I will need to debug it. If it works at 100,000, try smaller values until you find the lowest value where it works.

**Comment by tonyguadagno** [comment]
hi, i tried 100000 and got the same results, what can i provide to help you debug?  i am willing to give you the recording if you like?  let me know. thanks

**Comment by bennettpeter** [comment]
Please provide the recording. You can share it on Dropbox or Google Drive.

**Comment by tonyguadagno** [comment]
here you go, please let me know when you download it so i can delete.
thanks

https://drive.google.com/file/d/105CQj3_p0AbBBdiHkML8O-TeYqY0yvpq/view?usp=sharing

**Comment by bennettpeter** [comment]
I have downloaded the file. It plays fine with vlc but it does not play at all with leanfront on fire stick 4K. I just get a rotating circle. Are you using a fire stick or a shield? I will investigate what is going on.

**Comment by tonyguadagno** [comment]
hmm...interesting...so i am using leanfront on a fire stick 4k.  and the file does play for me, with the issues i listed above.....it seems to play fine on mythfrontend including ff and rew....not sure why it will not play for you...
also, this is not the only recording it has happened to, however, very few are like this.
let me know if i can provide more info.

**Comment by bennettpeter** [comment]
I have fixed this and posted a new apk (leanfront-release-v0-288-gaef474f.apk). Please try it and confirm whether it works.

**Comment by tonyguadagno** [comment]
Peter, perfect!!! works great.  thanks for your efforts

btw, what was the issue?

**Comment by bennettpeter** [comment]
Fixed in 696789c163f15f36e84c82fa64b708361c5f0bd6 .The code in Exoplayer was finding an incorrect end time, due to either corrupt data or misinterpretation of correct data. I added a sanity check to ensure it has a valid value. I shall be submitting the fix to Exoplayer.
