### ISSUE TITLE
feature request - Time of Day on menu

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#15]
hi, not sure if this is the right place for this, if you would like feature requests somewhere else, please let me know.

it would be helpful to have the time of day displayed on the leanfront menu.  i was thinking in the upper right, but just my 2 cents.

**Comment by bennettpeter** [comment]
When you say "On the menu" are you referring to the main page with the list of recording groups? The upper right has a MythTV icon on the main page and once you select a recording group or directory it has the recording group or directory name there.

I can try to fit in a time display if that is where you want it. Be aware that once you page down it disappears. Also there is a time display in the On Screen controls that display if you press a key while playing.

**Comment by tonyguadagno** [comment]
Peter,  I looked closer and I see your point. (both points) I still feel it would be helpful to have the tod.  maybe under the Myth icon and under the groups titles (for example, when you select livetv and the word livetv is displayed in the upper right) would be good?

thanks for considering

**Comment by bennettpeter** [comment]
Done in commit a2363dd - not released yet

**Comment by bennettpeter** [comment]
Feature Released in version leanfront-release-v0-301-gf554f7f.apk
