### ISSUE TITLE
feature request - sort episodes by season/episode

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#16]
it would be really helpful to be able to sort the episode list by season/episode as opposed to recording date.

thanks for all the effort!!!

**Comment by bennettpeter** [comment]
I suggest you sort by Original Air date, which is an option in the settings. This should be the same as season and episode. The thing I do not like about season/episode sorting is that when you have multiple series on one row, as in the "all" row, it does not make sense. Season 2 episode 2 of Chicago PD do not follow on season 2 episode 2 of Chicago Fire, but they may follow on from a different episode based on their original air date (on the occasions when there is a crossover).

**Comment by tonyguadagno** [comment]
ah, ok, i will check that out.

**Comment by tonyguadagno** [comment]
this works great, thanks for pointing me in the right direction!
