### ISSUE TITLE
Manage Recordings Issues

### ISSUE THREAD

**Issue by jksj461** [bennettpeter/android-MythTV-Leanfront#18]
Tested on Shield TV program version leanfront-release-v0-293-g9d16a1f.apk
Program Guide
In general the entries need to be brighter, they are difficult to read in daylight unless they are highlighted.
Clicking on an entry shows the program details and allows recordings to be set.
This only works once. Clicking on another entry does not work.
Once in this state when scrolling down the program names are blank.

Recording Rules
No issues

Upcoming Recordings
Works only once as in the Program Guide Page but in this case the screen blanks when the entry is closed
It would be useful if 'do not record this showing' was available for an entry.

Many thanks John Baker

**Comment by bennettpeter** [comment]
Thank you for pointing this out.
I have fixed the bug in version leanfront-release-v0-295-g0717692.apk.
Brightness of entry and "do not record this showing" are enhancements rather than bugs. If you still want these please open a separate request.
