### ISSUE TITLE
feature request - filter videos by parental control level

### ISSUE THREAD

**Issue by drwillis** [bennettpeter/android-MythTV-Leanfront#19]
Hi, 

Firt, this is excellent work. Thanks for sharing this.

I had a feature request to add a default parental control level setting for mythtv video filtering. 

The default parental control level (1-4) would be used to filter available videos and show only those videos having a parental control level of equal or lower value than the leanfront configured parental control level setting.
cheers!

**Comment by bennettpeter** [comment]
Added support for parental level on videos in commit 52b187a, not released yet. It does not support the PIN, so hope your children do not know how to get into settings. There is a setting at the bottom of program list options to specify the level - 1 2 3 or 4. Only those video below or equal to the level set will be visible. You will have to use mythfrontend to set the level on the videos, I have not built anything to do that in leanfront.

**Comment by bennettpeter** [comment]
Feature Released in version leanfront-release-v0-301-gf554f7f.apk
