### ISSUE TITLE
new feature request on settings

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#20]
Not sure if this is even possible, but it would be cool if the settings for forward/backward skips be per group. For example I have a Default group and a Sports group. They have separate skip values. Default is 60/-15. Sports is 30/-10.

Mythfrontend picks these up automatically. If that is not possible in Leanfront, then maybe a way to edit per group within Leanfront settings?

Leanfront does show my recordings by group.  All my Sports are created with the Sports template so they show up in the Sports group in Leanfront.  The rest are in the Default group/

**Comment by bennettpeter** [comment]
Each recording has a **recording** group and a **playback** group. Leanfront groups recordings by **recording** group. **Playback** group is what determines the jump forward and back amounts in mythfrontend. 

Can you confirm that you are using Sports **playback** group, so that I can be sure I do something that will work for you.

**Comment by jfabernathy** [comment]
Not sure it's called playback profile.  In mythfrontend -> Setup -> Video -> Playback Groups -> I have 2 groups: Default Group and Sports Group. Sports is set for 30 second fwd and 10 seconds back. Default is 60 fwd and 15 back. Then I make sure my rules for recorded pick the right Storage and Playback groups.
At least that's how mythfrontend works for me

**Comment by bennettpeter** [comment]
Sorry- yes it is playback groups not playback profile.

**Comment by bennettpeter** [comment]
This is done in release 20211206-leanfront-release-v0-308-gdfbe0f0.apk. See the documentation for details on playback groups.

**Comment by jfabernathy** [comment]
Great work.  Just what I wanted. shorter skips for sports and longer for regular recordings.
