### ISSUE TITLE
Pre-compiled binary

### ISSUE THREAD

**Issue by coliss86** [bennettpeter/android-MythTV-Leanfront#21]
Hi, 

Thanks for your work !

Would you mind updating the precompiled binary on https://dl.orangedox.com/pCBmBm please ?
I see that the latest was uploaded in February.

Thanks a lot !

**Comment by bennettpeter** [comment]
Thank you for pointing this out. I never noticed that the date was wrong.

Version leanfront-release-v0-306-g5f5ad43.apk was built on October 16th 2021. I don't know why Orangedox is showing February 18th. If you look at the prior versions directory they all have February 18th as the date. I will contact Orangedox to ask them about the incorrect dates.

That said, I am planning to release a new version in the next day or two, with some new features. It will probably still say date of February 18th unless I can figure out how to fix that.

**Comment by coliss86** [comment]
perfect, thanks !
