### ISSUE TITLE
Leanfront on Android Phone?

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#26]
This may not be supported but I thought I'd try it.  I downloaded and install Leanfront (20220213-leanfront-release-v0-338-ga03ae9e.apk) on my Galaxy S21 phone All I did to the setup was set the IP address of the backend.  I tried playing a recorded program which was a 1080i MPEG2 OTA .ts file from a HDHR tuner. I can hear the audio but the video is blank.  I can get it to play a video I have in the video storage group but those are all .m4v files with H.264 encoding.

Is this a settings issue or am I trying something not supported?

**Comment by bennettpeter** [comment]
Leanfront only supports hardware decoding, so if the phone does not support it you will not get a picture. 

The newest phones do not support MPEG2. MPEG2 support is optional in android. My prior phone did support it but my latest phone does not. Try on an old phone.

**Comment by jfabernathy** [comment]
Okay that explains it.  Not a priority. Just testing.
