### ISSUE TITLE
Advice where to post this...

### ISSUE THREAD

**Issue by tunerooster** [bennettpeter/android-MythTV-Leanfront#3]
I am not sure where to post this, but since Leanfront works, and arm
v31.0 does not, I thought you would be so kind as to direct me.

On my 2017 Shield TV I have installed: _mythfrontend-20190724-arm64-v31-Pre-539...apk_
On a new 2019 Shield TV (Tube): _mythfrontend-20200716-arm-v31.0-79-g89d1991ef2.apk_

The _20190724-arm64-v31-Pre-539_ works fine.

The new _20200716-arm-v31.0-79_ has problems as follows.  When seeking:

1. The audio does not mute when seeking, as it does on _20190724-arm64-v31-Pre-539_.
2. The _audio sync_ gets messed up when seeking, and causes the video to play double speed and without audio.

I did notice the _AVSync2_ menu option is missing from the
_Settings->Playback_ menus on _20200716-arm-v31.0-79_, and I *do* have it
set on the _20190724-arm64-v31-Pre-539_ version.

As I mentioned, on the Shield Tube, the leanback-frontend play and seeks
without error.

Thanks and thanks again for your contributions to MythTV, and for any
help you can offer.

P.S. I have been a devoted MythTV user for 18 years, since the initial
release!

**Comment by bennettpeter** [comment]
For the mythtv problems it is best to use the mythtv tickets or mailing list. If there are changes between v31-Pre and v31.0 they are likely caused by the OpenGL changes done by Mark and he may know what is happening there. One of the changes is that all playback uses avsync2 now, the original avsync was removed, so that is why avsync2 is not in the setup.

You said that leanfront plays and seeks with error. What is the error? Or did you mean WITHOUT error?

**Comment by tunerooster** [comment]
I meant *WITHOUT* error.  Sorry, I have fixed my post.

**Comment by tunerooster** [comment]
I meant *WITHOUT* error.  Sorry, I have my post.

Should I contact Mark directly, or just post in mythtv tickets at:
https://github.com/MythTV/mythtv
If Mark, how do I contact him?

**Comment by tunerooster** [comment]
As you suggested, I tried to post this on https://github.com/MythTV/mythtv but there is no "issues" tab.  How do I post this there?  Please advise...  Thanks!

**Comment by bennettpeter** [comment]
Currently the ticket site is https://code.mythtv.org/trac (login with github id) but as from September 1st the plan is to open up the issues page on  https://github.com/MythTV/mythtv
