### ISSUE TITLE
deleted recordings not showing as deleted until refresh

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#35]
using 358 version.  This morning I was viewing a recording that was in progress.  I started watching at a little after 8:00 but the recording had started at 7:00.  I watched it for 20 minutes then skipped 10 minutes and then watch for 20 minutes. At that point I was done watching but the program still had 10 minutes or so left to record.  

I hit back and then selected other action and selected delete.  No icon of the wastebasket showed. I backed all the way out and it still showed one program in the News recording group. I selected refresh from the tools and then the News group went away and the Deleted group now showed 1 item.

Not a big deal, but  if you can find this bug, it would be great.

**Comment by jfabernathy** [comment]
I did a test case where I stopped the recording before deleting and it updated the list without refresh. THanks.

However, I noticed while using Leanfront to setup the recording from the Program Guide that It marked the recording as Tuning and I watch for that to change to recording and after about 10 seconds, I just went back and the main screen didn't show any new items in the Default group.  So I refreshed and then I had the program listed.

Now my test was of a program already in progress that was half over. I just selected that and then chose record only this program. I'll try doing a recording in the future as another test.

**Comment by jfabernathy** [comment]
On this test I setup to record a program using Leanfront tools and selected a program starting about 10 minutes from that time.I backed out and saw the program as a part of Upcoming recordings. I backed completely out of LF and did something else for 20 minutes.  When I started LF again the top display showed All, Default, LiveTV, Videos, and Tools.  The number under Default showed 2.  I have multiple shows within 2 series so I expected to see 3 which would have meant those 2 series plus the new recording.  I did not hit refresh at that time, but selected Default and saw that I indeed had my 2 series of recordings plus the new program.

I started watching the new recording and then backed out, stopped the recording and then deleted the recording prior to it finishing.  As I backed out it had already refreshed the list showing 1 in Deleted and only 2 series in Default which was correct.  So while this is trivial, the only issue would seem to be the number under Default at startup not reflecting the current recording in Default. Not really an issue. During a normal fall new program introductions, I have no idea how many series of programs I have recorded in any recording group.

BTW, I'm going to add a suggestion for future features.

**Comment by bennettpeter** [comment]
Leanfront does not work the same as mythfrontend. mythfrontend gets immediate updates from the backend as soon as they happen, but leanfront only gets updates when it requests a refresh. It does a refeesh when it starts up, and does a limited refresh of just one show when you delete a show, mark it as viewed, etc. It also does a full refresh once per hour. As a result of this there will be situations where it has outdated information, but hopefully not more than 1 hour out of date.

At startup, you can tell if it has done the initial refresh by looking for the usage percentage next to the magnifying glass at the top of the screen. That percentage only appears after it has completed a refresh.

**Comment by jfabernathy** [comment]
Thanks for the explanation.  So the initial refresh at startup may take longer than I was waiting for. I'll use the % Usage as a key, but usually not a problem.
 
As to the stopping a recording prior to deleting, is it possible that the Delete option could be grayed out for current recordings until they are Stopped first? This is an old habit for me as I've use mythfrontend since the dawn of time and I've always just deleted a recording when I done with it regardless of whether or not it's still recording.

Either way I now know the issues. Thanks, it's a great app.

**Comment by bennettpeter** [comment]
I will look into the delete and stop functions. Whet the app does is to only show options that are applicable, so it would mean not showing "delete" while a recording is in progress.

**Comment by bennettpeter** [comment]
Actually, on investigation, deleting a recording in progress is fine. It stops it and deletes it. I just need to fix the refresh after delete, which is a simple fix. Also the refresh after stop is also not working correctly, it is still showing stop as an option after it was already stopped. New version will fix these in a couple of days.

**Comment by jfabernathy** [comment]
Thanks, I tested this morning against an in-progress recording and deleted without stopping and it worked perfectly. The refreshes also worked as expected.
