### ISSUE TITLE
Leanfront fails to play recordings on VM backend.

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#39]
First this is not critical, but I discovered it during testing some different backend configurations using a VM.  I got my backend working under libvirt/kvm and I could even run the frontend but the video quality was a little jerky, so I wanted to test it with a remote frontend to see if this was purely a lack of video acceleration under the VM.  So I set up my Leanfront on my FIreTV 4K to point to the backend running on the VM.  BTW, I disabled the firewalld on the VM so that wouldn't trip me up.  

When I changed the backend IP on Leanfront  and refreshed I saw the one recording I had, but I could not play it.  After a few seconds of spinning circles, I got an error message:

"Play Failed. Unable to obtain file length." 

If I select continue, I get another error: 

Playback Failed. Error Loading data from the MediaSource. Source error.

This was all using Status Port 6744.  Which is what I use for Leanfront with my Production backend. But I get the same error with Port 6544.

My PC running the VM has a Network Bridge setup so all VMs are on the same subnet as my HDHR tuners and all my FIreTV 4k sticks.

Any idea why this isn't working?

BTW, Kodi with the mythtv plugin on my FireTV 4K stick plays against that VM backend okay.

**Comment by bennettpeter** [comment]
leanfront uses http on the specified port to access the lists as well as the actual playback data. So it should work

If it can see the list but not play the video, most likely is that the ip address in backend settings is wrong. On the backend run mythtv-setup, general, host address backend settings and check the primary ip address/DNS name. Make sure that is the same ip address that you have used in the leanfront setup.

**Comment by jfabernathy** [comment]
my IP setup in mythtv-setup used 127.0.0.1. I changed that to the actual IP address and Leanfront now works.
