### ISSUE TITLE
Request: Skip to Next Segment

### ISSUE THREAD

**Issue by kmand** [bennettpeter/android-MythTV-Leanfront#44]
I frequently watch news oriented programs that have independent stories separated by commercial breaks. It would be desirable to be able skip the current one (it could be of little interest). Mythrfrontend has this by z and q. Personally I rarely use the fast forward and reverse buttons and would like an option to have them do z and q.

**Comment by bennettpeter** [comment]
This is now done in 20221125-leanfront-release-v0-396-g0e39d23. It allows you to assign various keys to the commercial skip operation (the q and z equivalents). Also the |< and >| icons will perform the commercial skip back and forward.
