### ISSUE TITLE
Request : Sleep timer

### ISSUE THREAD

**Issue by kmand** [bennettpeter/android-MythTV-Leanfront#45]
I often use leanfront in my bedroom. It would be nice to have a sleep timer option that pauses after a specified time.

**Comment by bennettpeter** [comment]
Have you tried the Android system and android apps? If something is provided another way, I would prefer not to duplicate it. Perhaps these methods do not work if leanfront is busy playing, in which case I can look into it.

https://play.google.com/store/apps/details?id=com.neon.sleeptvtimer&hl=en_US&gl=US&pli=1
https://ugtechmag.com/how-to-set-sleep-timer-idle-tv-standby-on-your-android-tv/

I have not tried these or any other Android methods of invoking sleep. I have mine set on Never Sleep. Let me know if any of this solves your problem.
