### ISSUE TITLE
LiveTV repeat loop

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#46]
We were noticing a situation with Leanfront where LiveTV would startup and play 10-15 seconds and then repeat the same sequence a few times. Pressing direction arrows seemed to make it stop the loop.

I think this maybe a case of someone trying to start LiveTV on one FireTV using Leanfront not knowing that the channel was already being recorded by someone else on another FireTV.

I view this as a minor issue as the second person could just watch the recorded file.  But this can happen in our house as for example I record channel 5_1 from 10-11pm with some extra time in case the program runs late. At 11pm my wife starts LiveTV on channel 5_1 expecting the News.

**Comment by jfabernathy** [comment]
I have had the looping happen when nothing else was recording and only one FireTV 4K stick using the LiveTV feature.  It's not 100%, but happens at times.  I can get by it by clicking the right arrow multiple times

**Comment by bennettpeter** [comment]
I don't know what is causing this.

When this happens, what do the on screen controls show? Do they pop up when it repeats? Do they show a length at the end or do they show "--" for the length, or perhaps they alternate between a time and "--" ? If possible could you take a video of this happening.

**Comment by jfabernathy** [comment]
To the best of my recollection, there is no pop up menu when it loops until I press right arrow to get out of it. The next time I see it.  I'll note the menu.

**Comment by jfabernathy** [comment]
Last night I was recording channel 5_1 with mythtv and watching it in the Den delayed by a few minutes.  I stopped that Leanfront and went into the bedroom and was going to put on the news via LiveTV but I ending up picking 5_1 again the same as was being recording. After about 15 seconds of playing, it skipped back to what it started on and there was no popup menu. It did the repeat twice and then went on.  I can also force it out of looping by the right arrow.

**Comment by bennettpeter** [comment]
Regarding pop-up menu, what I was actually asking about is whether the on-screen controls (progress bar, etc.) show when it happens.

**Comment by jfabernathy** [comment]
Nothing shows on the screen when it loops back except the "waiting" circle for a fraction of a second

**Comment by bennettpeter** [comment]
I do not use Live TV with leanfront, so I have not experienced the problems. I ran a test today, and I cannot get your situation to happen. 

I did find that if you increase the speed during Live TV it acts rather crazy, speeding up and pausing repeatedly. I need to put something in to prevent that. When playback catches up to real time it needs to revert to normal speed.

Also i found that if you have a dialog open (e.g. dialog to change speed, change subtitle, change audio, etc), when the player catches up to the initial file length, the dialog gets overwritten and you can land up with several copies of the dialog overlaying each other. This also needs to be fixed.

Have you used any of the on-screen dialogs when the looping happens? Anything you know that could trigger it?

**Comment by jfabernathy** [comment]
The looping only happens once in a while.  Very hard to reproduce, but usually when something is recording at the same time. It's hard to identify how to reproduce it.  When it happens nothing is on the screen but the LiveTV. No on-screen dialog.  When it loops back you see the delay circle indication for a fraction of a second, but no OSD. I do not use the speed change.  Never have. On recording playback, I use right arrows to skip 1 minute forward and left arrow to skip 15 seconds backwards depending on playback profile. I have the up and down arrows set for 10 minute jumps.

**Comment by bennettpeter** [comment]
I have fixed a number of bugs, some of them affecting Live TV, in new version 20230108-leanfront-release-v0-400-g2790c7c.apk. I have not managed to recreate the skipping back situation or understand why it happens. Perhaps the fixes I made will help.

**Comment by jfabernathy** [comment]
I've installed 400 and will be watching for any looping.

**Comment by jfabernathy** [comment]
I have not seen any looping with live broadcast even when also recordings the same channel.  Let consider this fixed with whatever you recently changed.
