### ISSUE TITLE
Runtime Exception error

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#47]
Peter, Hi, i recently upgraded to the current version to get the commercial skip features.  they work great but i have noticed that after a skip (sometimes but not always), the app will start to spin and never come back.  if i press the back button on the remote, it goes back to the menu and a message appears on the screen saying, "unhandled runtime exception".  when i hit play again, the recording picked up where it should at the end of the commercial set.  i have noticed that on one occasion, this happened when i first started to play a recorded show from the biggening as well.

this seem to have started when i installed the versions of the app that had commercial skip in it.

thanks again for your efforts on this app!  I am sure the boat loads of money you are making make it all worthwhile!!! LOL

**Comment by tonyguadagno** [comment]
Peter, ok, it took a while, but i have some info for you.  here are the details

I was watching a recording and, in the middle, (not a commercial etc)..the playback froze, and I got the spinner.  at that point, I started the logcat and got logcat.txt

after i stopped logcat, i returned to the menu.  i noticed that it had lost its place, there was no option to play from bookmark.  I pressed "play from beginning" and it immediately started spinning again.  so I started logcat and got logcat2.txt

after i stopped logcat, i returned to the menu.  i then started logcat3.txt and then pressed "play from beginning".  i got the spinner and i saved logcat3.txt


i have uploaded all 3, i hope one of these helps.

let me know if you need more.
thanks for your efforts
[logcat2.txt](https://github.com/bennettpeter/android-MythTV-Leanfront/files/10142088/logcat2.txt)
[logcat3.txt](https://github.com/bennettpeter/android-MythTV-Leanfront/files/10142089/logcat3.txt)
[logcat.txt](https://github.com/bennettpeter/android-MythTV-Leanfront/files/10142090/logcat.txt)

**Comment by bennettpeter** [comment]
I see it is getting a "Player release timed out" error from Exoplayer.

This has been reported by other apps that use Exoplayer:
https://github.com/google/ExoPlayer/issues/9823

They indicate it may be specific to the video file. Can you reproduce it on the same file? If so maybe you can send me a part of the file so I can try to reproduce it.

There are also messages that indicate the system may be overloaded or short on memory.

What type of fire stick are you using? The above bug shows fire stick lite.

It looks like your recording has comm break data. Do you have auto skipping enabled?

**Comment by bennettpeter** [comment]
If the problem can be reproduced on that file, please share it.

Please also supply the skip list, which can be extracted this way
mythutil --getskiplist --chanid 10738 --starttime '2020-08-17 20:00:00' -q

You get a one-line response similar to this:
Commercial Skip List: 1-1017,12581-25019,68124-69963,98054-114317,142223-154904,193282-195113,215510-215511

**Comment by bennettpeter** [comment]
Please share the file or a file extract that can reproduce the problem.

**Comment by bennettpeter** [comment]
If you have a recording I can test with, please re-open the issue and supply a sample.

**Comment by tonyguadagno** [comment]
peter, i am really sorry for ghosting you.  i have the info you requested.  i would like to dm you the download link if thats ok

$ mythutil --getskiplist --chanid 1132 --starttime '2022-12-17 22:00:00' -q
Commercial Skip List: 0-1696,38605-44061,64890-72122,108020-121638,158588-176859,210122-216231

**Comment by bennettpeter** [comment]
You can send it to my email pb.mythtv at gmail.com or message me on libera chat (peterbennett).

**Comment by tonyguadagno** [comment]
Peter, here is the download link for the recording.  Please let  me know when you have it so I can take down the file
Thanks

https://drive.google.com/file/d/1CfmuonhyUYU9H3wVSXn0TJHxiGSgx6PI/view?usp=sharing

Tony

**Comment by bennettpeter** [comment]
I have downloaded the file.

**Comment by bennettpeter** [comment]
I played that whole file, skipping forward 1 minute at a time. When it hit a commercial break, it skipped the break. Most skips were slow, with a spinning progress bar for a few seconds. I also tried pressing back during the spinning, but that returned to the video details page correctly.

Do you have any way of recreating the error? I can't do much with it otherwise.
