### ISSUE TITLE
Request: playback speed as global option

### ISSUE THREAD

**Issue by petropolis100** [bennettpeter/android-MythTV-Leanfront#49]
I like to watch everything at 1.7x the speed. Can we make this a global option so I don't have to reset it every time I watch a video?

**Comment by bennettpeter** [comment]
mythfrontend has time stretch set as a playback group setting. I can do likewise and add it to the playback group, so you can have it as a default for selected groups.

**Comment by bennettpeter** [comment]
Done in version 20230111-leanfront-release-v0-401-gf9c2b52.
