### ISSUE TITLE
Live tv

### ISSUE THREAD

**Issue by jseagull1** [bennettpeter/android-MythTV-Leanfront#5]
Hello Peter, when playing a live tv channel does it always record? I don't need any recordings if I just want to watch. I am using your software on a 4k Firestick and it will stop playing and spin for a bit (like a weak signal) and start up again. The Firestick is 8' from the router and I don't have an issue watching 4k stuff on Amazon. That is why I was wondering if recording at the same time as watching tv could create a bottleneck or if there is something else to try. It doesn't seem to happen when watching a non-HD channel.

Thank you for the software.
John

**Comment by bennettpeter** [comment]
Yes it always records. Does it do this stopping a lot? Make sure you are using wifi on the 5 Ghz band if the signal is MPEG-2. HD MPEG2 could use more bandwidth than 4k stuff from amazon. 

Does this only happen when watching LiveTV, or is it also when watching recordings from the same channel? If recordings are OK then the wifi speed is not the problem.

LiveTV could occasionally pause for a few seconds to catch up, soon after starting or after using a skip forward, but it should settle down after a minute or so.

**Comment by jseagull1** [comment]
Hi Peter, I only have a 2.4 router. It stops a lot on an HD tv channel (like it is catching up) and stopped once on a old tv series. Playing back a recorded video is fine with no stops. Is there a setting I can change to cut 4k down a bit?

**Comment by bennettpeter** [comment]
It depends on the bit stream. If you play a recording from that same channel that is giving problems, is it OK? Is Live TV bad on all HD channels? Some channels can have a higher bitrate than others, and this will be reflected in both recordings and Live TV.

Also, make sure you have the latest version of leanfront, there have been some fixes to Live TV.

If this does in fact affect recordings from the same channel that has the problem, then it is likely a wifi bandwidth issue. you can upgrade your router or get an ethernet adapter for the fire stick ($15 from amazon) and use a wired connection.

**Comment by jseagull1** [comment]
Hello Peter, I purchased an ethernet adapter as suggested and it works perfectly. No delay or buffering. 
Thank you.
