### ISSUE TITLE
Manual recording as an addition?

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#53]
I think it would be a great addition to Leanfront to be able to set a manual recording. I would envision a Manual Recording option that had the following selection:

- Title
- Channel
- start time
- duration or end time

**Comment by bennettpeter** [comment]
Done in 20230117-leanfront-release-v0-405-g164dd7e. 

To create a manual recording, go to manage recordings, recording rules. Select the cell  labeled "Schedule New Recording".

It includes all the fields in the manual record page of mythfrontend, plus subtitle. Title and subtitle are optional.

**Comment by jfabernathy** [comment]
Works perfectly. Thanks very much.
