### ISSUE TITLE
Feature request: Add Playback Data function

### ISSUE THREAD

**Issue by jusmop** [bennettpeter/android-MythTV-Leanfront#55]
I'm thinking of the same function that is available in MythTV Frontend during playback. See, for example:
https://photos.app.goo.gl/zy9vJkQoP3YS91ur6

**Comment by Jpilk** [comment]
Similar info can be shown in playback with mpv.  Just press 'i'.

**Comment by bennettpeter** [comment]
Playback is handled by Exoplayer, unlike mythfrontend which has its own player code. The same data that is shown on mythfrontend is not easily available. Stats that are available are here (see fields and "get" methods on this page):
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/analytics/PlaybackStats.html
The  video audio and subtitle format are also available, see here
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Format.html
Unfortunately I know from experience that some of these things, for example the framerate, return "NO_VALUE" so they are useless.

If there is anything useful in here I could add a menu that can display it. What do you think would be useful?

**Comment by bennettpeter** [comment]
Closed due to a lack of response to my question.
