### ISSUE TITLE
Frame rate matching on/off

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#56]
In recent discussions I've seen where it was advised to turn off Frame Rate adjustment on Leanfront. I went to look for that setting in my Sony TV Google TV app (v0-399) and didn't see it anymore. When I use to use a FireTV 4K I remember having  this settings. Did you remove it since it may not be working?

**Comment by bennettpeter** [comment]
It is in Playback:Default and in Playback for other playback groups if you have them. Do you not see it ther?
![Screenshot_2023-01-02_11-24-51](https://user-images.githubusercontent.com/8069726/210257462-dd0891a7-f231-4343-b6ea-fa4b15092d5e.png)

**Comment by jfabernathy** [comment]
Thanks for the pointer. Yes, it's there. So I'll turn is off. It was on but I had no issues here in the USA since all content from OTA is 60Hz

**Comment by jfabernathy** [comment]
I'll close
