### ISSUE TITLE
Is there any chance to have the left menu use Display Groups instead of Recording Groups?

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#59]
Is there any chance to have the left menu have a choice to use Display Groups instead of Recording Groups?

It'd be nice to group shows together without having to create new recording groups, especially when it might be a limited series or marathon you've recorded, will watch, then delete.

Thanks,

**Comment by bennettpeter** [comment]
There isn't a feature for "Display Groups" in MythTV. Did you mean Playback groups?

The organization of leanfront mirrors what mythfrontend does, organizing recordings  by recording group, plus combining them all in a row called "All".

There are several ways you can navigate the recordings, perhaps you are not aware.
- Press enter when on a row header (left column) opens a page with a row for each series.
- Press enter on an item in a row, brings up the details page for that item. When on the details page press down arrow to see other episodes of the series (Marked "Related Videos")

I find it convenient to use the row marked "Recently Viewed" to find a series I have been watching, then from the details page down arrow to find the next episode. You need to enable the Recently viewed list in the settings.

You can customize the sort order and what is included in the related video and recently viewed lists in the settings.

Finally, it is not difficult to create recording groups, and you can move recordings to a different recording group if you need to. This requires mythfrontend. You can run mythfrontend on a laptop and operate it with the keyboard to do this.

**Comment by dheian** [comment]
Didn't know the "hit enter" move. Thanks.

**Comment by bennettpeter** [comment]
I have updated the documentation recently. Let me know if anything is not clear
https://github.com/bennettpeter/android-MythTV-Leanfront#readme
