### ISSUE TITLE
Upcoming Recordings - description is not related to that showing

### ISSUE THREAD

**Issue by jksj461** [bennettpeter/android-MythTV-Leanfront#60]
20230227-leanfront-release-v0-418-ge373675
On the Upcoming Recordings listing (the details shown when the entry is clicked). These details are different from those shown on the listing page. Those on the listing page are correct in that they are related to that showing whereas on Upcoming Recordings the description maybe from when that program was first recorded.
This issue is not new and is unrelated to the recent updates so maybe a desired feature?
However if the entry for that showing is available it would be useful to show it.

**Comment by bennettpeter** [comment]
The page you get when you press enter in upcoming recordings is the edit recording rule page and it is showing the details from the recording rule, which are the details from the first time you created the rule. Clearly they are not useful once you are past the first episode. I will take a look and see what I can do about this.

**Comment by bennettpeter** [comment]
Fixed in release 20230311-leanfront-release-v0-422-g3f16be0.apk
