### ISSUE TITLE
Tools > Backend Status shows only Library API version and not MythTV Version

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#61]
Is there a way that the Tools > Backend Status screen could show the MythTV Version? The only way I can get that now is by use of a computer via ssh or mythweb. If using Leanfront as your primary frontend it would be helpful to have that information without pulling out a laptop.

**Comment by bennettpeter** [comment]
The backend Status screen is just a copy of the web page at
http://backend:6744/Status/Status
There is also a feature built into MythTV to add your own customization to that web page.
In mythtv-setup, go to General -> Miscellaneous Settings. In the box for "Miscellaneous Status Application" enter the following:
`mythutil  -q --version | head -n 2 | tail -n 1`
Then you will see the version listed at the end of the status display (down arrow to get to the end)

**Comment by jfabernathy** [comment]
Thanks, that works on Leanfront and on mythweb backend status.  However, it doesn't work on http:192.168.8.243:6744/status or status/status. Since I only use mythweb and leanfront, I'm all set.  Thanks.

**Comment by bennettpeter** [comment]
That URL is case sensitive, (and it needs slashes) as in  http://192.168.8.243:6744/Status/Status .

**Comment by jfabernathy** [comment]
That works great.
