### ISSUE TITLE
AV sync in LiveTV

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#63]
On one of our TVs we have a FireTV 4K and a sound bar.  The sound bar is connected via SPIDF optical cable to the TV audio out.  I can use the Fire TV settings to set the AV sync and that works for most Apps.  However for Leanfront I need to use it's AV sync while playing a recorded program.  Once set it works but will have to be reset for each use.  I can't find a way to use the AV sync for Live TV.

It would be great if the AV sync setting could be saved as a baseline for all uses that could include LiveTV.

**Comment by bennettpeter** [comment]
There is already a setting. Settings->Playback:Default->Audio Sync Adjustment in milliseconds.

Is there a problem with it, or does it not work? Maybe it does not work for LiveTV. Does it show a section for Playback:LiveTV ? I am not sure since I don't use LiveTV.

**Comment by jfabernathy** [comment]
Great, found the setting. Sorry I didn't look all the way down under Default.  That does solve it for both recordings and LiveTV.  Before I was able to set it permanently, fixing AV sync on recordings was possible but just annoying to do it each time. On LiveTV if you tried to do AV sync to positive values it would just go back to the Menu for Play Live TV. Some times it would work going negative values, but sometimes it would go back to the Play Live menu.

So for the sound bar, I set it to -170 and save that in Settings-> Playback:Default -> Audio Sync Adjustment as -170 and just about everything is in sync including LiveTV.

So the learning is to find out the setting with Recorded TV and then update the settings and LiveTV will take care of itself.

Thanks a bunch.  My wife is now happy.  I would never have lived with lip sync issues as long as she had. Once I used her TV I immediately started researching the issue.  My TV in the Den has never had a AV sync issue on Leanfront with either the FireTV 4K Max or Sony Google TV.  We both stream from the same backend in the data closet.

**Comment by bennettpeter** [comment]
Perhaps it will work in Live TV if you pause playback for a few seconds first before adjusting the sync.

**Comment by jfabernathy** [comment]
I've spent a fair amount of time and I have come to the concluded that if you can get the FireTV stick AV sync perfect, then Leanfont will not need anything in it's AV Sync field.  The FireTV AV sync was harder to get correct to me than Leanfront.  But what I did was put the FireTV sync at the same relative position as I did on the Leanfront sync screen. That made the biggest difference.  I found the FireTV method harder to figure out.  But once it was obvious it was correct, leanfront could be put back to zero and all was well.
