### ISSUE TITLE
"Change Audio Track" results in "Unexpected Runtime Exception" and "Playback Failed"

### ISSUE THREAD

**Issue by bobMuk** [bennettpeter/android-MythTV-Leanfront#7]
Great piece of software - thanks for all the effort you've put in!

I installed yesterday and found that many recordings don't have any audio.  If I use "Change audio track" (and the runtime exception doesn't occur) then it does find the audio and plays fine.  However something like 95% of the time when I click "Change Audio Track" I get the runtime exception.

I'm on mythtvbackend 31 and running the current latest version of leanfront (leanfront-v0-218-gd488336) on a Fire TV 4K

In the Fire TV settings I've disabled surround and have stereo only.

It looks like there's a way to retrieve logs with adb, if I can set this up would they be of any use?  I can also provide an example recording if that's any use.

**Comment by bobMuk** [comment]
Using adb turned out to be trivial, I had no idea :)

 $ adb logcat lfe:D *:S
- waiting for device -
--------- beginning of system
--------- beginning of main
10-29 16:41:11.898  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:12.945  5677  5677 I lfe     : PlaybackFragment File Length changed from -1 to 908560572
10-29 16:41:31.949  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:31.949  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:31.949  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:31.949  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:31.949  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:31.949  5677  5677 E lfe     :      at c.b.a.a.m0.d0()
10-29 16:41:31.949  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:31.949  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:31.949  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:31.949  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:31.949  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:31.949  5677  5677 E lfe     :      ... 8 more
10-29 16:41:31.949  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:31.949  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:31.949  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:31.954  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:32.219  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:32.219  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.m0.n()
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.m0.A()
10-29 16:41:32.219  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:32.219  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:32.219  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:32.219  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:32.219  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:32.219  5677  5677 E lfe     :      ... 9 more
10-29 16:41:32.219  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:32.219  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:32.219  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:32.984  5677  5677 I lfe     : PlaybackFragment File Length changed from -1 to 908560572
10-29 16:41:35.432  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:35.671  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:35.671  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.m0.n()
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.m0.A()
10-29 16:41:35.671  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:35.671  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:35.671  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:35.671  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:35.671  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:35.671  5677  5677 E lfe     :      ... 9 more
10-29 16:41:35.671  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:35.671  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:35.671  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:35.676  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:35.906  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:35.906  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.m0.n()
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.m0.A()
10-29 16:41:35.906  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:35.906  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:35.906  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:35.906  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:35.906  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:35.906  5677  5677 E lfe     :      ... 9 more
10-29 16:41:35.906  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:35.906  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:35.906  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:36.441  5677  5677 I lfe     : PlaybackFragment File Length changed from -1 to 908560572
10-29 16:41:37.456  5677  5677 I lfe     : PlaybackFragment File Length changed from 908560572 to 908560572
10-29 16:41:37.685  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:37.939  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:37.939  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.m0.n()
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.m0.A()
10-29 16:41:37.939  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:37.939  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:37.939  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:37.939  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:37.939  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:37.939  5677  5677 E lfe     :      ... 9 more
10-29 16:41:37.939  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:37.939  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:37.939  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:37.943  5677  5677 I lfe     : PlaybackFragment Playing offset mSec:0
10-29 16:41:38.189  5677  5677 E lfe     : PlaybackFragment Player Error Hell's Kitchen http://192.168.1.6:6544/Content/GetFile?StorageGroup=Default&FileName=/20006_20201022195800.ts
10-29 16:41:38.189  5677  5677 E lfe     : c.b.a.a.k0: Unexpected runtime error
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.i0.b()
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.m0.m()
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.m0.o()
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.m0.n()
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.m0.A()
10-29 16:41:38.189  5677  5677 E lfe     :      at c.b.a.a.m0.handleMessage()
10-29 16:41:38.189  5677  5677 E lfe     :      at android.os.Handler.dispatchMessage(Handler.java:98)
10-29 16:41:38.189  5677  5677 E lfe     :      at android.os.Looper.loop(Looper.java:154)
10-29 16:41:38.189  5677  5677 E lfe     :      at android.os.HandlerThread.run(HandlerThread.java:61)
10-29 16:41:38.189  5677  5677 E lfe     : Caused by: java.lang.IllegalStateException: Multiple renderer media clocks enabled.
10-29 16:41:38.189  5677  5677 E lfe     :      ... 9 more
10-29 16:41:38.189  5677  5677 E lfe     : PlaybackFragment Player Error Unexpected Runtime Exception
10-29 16:41:38.189  5677  5677 E lfe     : Unexpected runtime error
10-29 16:41:38.189  5677  5677 E lfe     : Multiple renderer media clocks enabled.
10-29 16:41:38.694  5677  5677 I lfe     : PlaybackFragment File Length changed from -1 to 908560572
10-29 16:41:39.702  5677  5677 I lfe     : PlaybackFragment File Length changed from 908560572 to 908560572

**Comment by bobMuk** [comment]
BTW - it looks like where I've said "no audio", it infact seems to be selecting the "descriptive" audio track.  This specific recording starts with some commercials before the actual programme starts and the commercials appear to have audio-description, while the actual programme that I've recorded does not (so the programme is silent throughout).

**Comment by bennettpeter** [comment]
This error occurs when there is mpeg2 audio that the fire stick does not support. A workaround is to select ffmpeg in the audio selections.

**Comment by bobMuk** [comment]
Thanks Peter - I thought I'd tried changing the audio to ffmpeg but it did indeed fix it.  So far I've not tried a recording that doesn't like ffmpeg so I think we're good.
Is there anything that can be done about the wrong audio track being selected?  It's not the biggest chore in the world to manually select the correct one but it'd be nice to not need to.

**Comment by bennettpeter** [comment]
How often does it select the wrong track? If it is more than an occasional problem I can look into providing some sort of setting to select a different audio track.

**Comment by bobMuk** [comment]
I did some testing with various recordings and it does seem to only be this programme (though multiple weekly recordings of it - I guess it could be anything from this channel but I rarely watch anything on it).  So I'm happy to close this.  Thanks again!
