### ISSUE TITLE
Suddenly lost playback a few days after installing new leanfront

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#70]
Running v33 of MythTV
Installed the 20231018 leanfront a few days ago.

I had no problems doing playback the last few days. Suddenly today, I can't seem to play any of my recordings. Both the backend and leanfront are set to 6744.

I used adb to capture a log. I hope this is enough of a snippet. If in future there's anyway to grep just the lines important to leanfront, please let me know.
[leanfront-snippet.txt](https://github.com/bennettpeter/android-MythTV-Leanfront/files/13170860/leanfront-snippet.txt)

**Comment by bennettpeter** [comment]
There is not much to go on here. Nothing in that log snippet reveals anything wrong.
What is the symptom? Is there an error message? Please describe what you do and what you see.
What android TV device are you running on?
Does the leanfront app crash?

**Comment by dheian** [comment]
Sorry...
Chromecast with Google TV. As I said, worked fine a few days ago even after the 20231018 upgrade.

Go into the app. It displays the recordings and thumbnails. I select a recording. It just displays the spinner. About 30-40 seconds later, it displays the show name and the timeline with the controls Gui. Once it even displayed the commercial skip message, but still no video. Odd since its worked flawlessly. Heading to bed early today, but will restart backend and Chromecast tomorrow morning and try again.

**Comment by dheian** [comment]
After a couple of reboots, it worked this morning. Ghost in the machine? 🤷‍♂️

**Comment by bennettpeter** [comment]
I suspect your backend was hung.
