### ISSUE TITLE
Feature Request: search guide by category

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#71]
It'd be great if we could search the guide by category so that we could just see, for example, what movies are in the guide.

**Comment by bennettpeter** [comment]
The categories do not include "Movies". See attached for the category list

https://pastebin.com/j0JuKA39

If you want to say "Musical Comedy" and it will search on that, I could implement it, but I don't know if that would be useful.

**Comment by dheian** [comment]
I guess I mixed up categories and lists. In the mythfrontend, you can you can get a list of movies and narrow it down by 🌟 rating. Or get a list of premieres.

**Comment by dheian** [comment]
Thanks. Really enjoying both the web frontend and leanfront. Thanks for your work.
