### ISSUE TITLE
no video on pixel 7 with android 14

### ISSUE THREAD

**Issue by tonyguadagno** [bennettpeter/android-MythTV-Leanfront#73]
hi, I just got around to trying this on my pixel 7 andriod 14.  the menu's look fine and when i play a recording, the sound is fine as well, however, i just get a black screen, no video....

am i doing something wrong?
thanks

**Comment by bennettpeter** [comment]
Some phones do not support MPEG2 decoding. If you play a H264 or H265 recording it will work.

**Comment by tonyguadagno** [comment]
ok, got it,  is there anything you can install to make the phone decode mpeg2?  a software package etc?

thanks anyway!

**Comment by bennettpeter** [comment]
There is something i n the works in Exoplayer called ExperimentalFfmpegVideoRenderer which may support it. It only exists in the development branch at the moment, whereas I use the release branch.

**Comment by tonyguadagno** [comment]
ok, good to know.

thanks again

**Comment by bennettpeter** [comment]
ExperimentalFfmpegVideoRenderer was last worked on 2 years ago, so I don't hold out much hope. The code is just a skeleton of what is needed.
