### ISSUE TITLE
Manage Recordings in Tools not always there.

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#77]
I have noticed recently that Manage Recordings only shows up in Tools when I'm at the top level where I see on the left side All, Default, LiveTV, Sports, Videos, and Tools. If I click into Defaults for example I see the list of shows and Tools at the bottom, but in Tools I only see Settings, Refresh Lists, and Backend Status.

This happens with all the top categories like Default, LiveTV, Sports, etc.

This is new behavior to me.  I found it because when I opened Leanfront I went down to Sports and clicked select then in the list of Sports I saw NFL Football, and click again.  So I click on NFL Football and only saw one game so I move down to the tools and Manage Recordings was missing.  I had to back out to the top level and then go to tools to find Manage Recordings.

**Comment by bennettpeter** [comment]
I made  a change to hide Manage Recordings if there were no channels. I forgot about the case where you are in a recording group and there are no channels there.

The reason I made the change was for the amazon app store. They require  to test the app before releasing to the app store. I did not want them trying to run Live TV or trying to schedule recordings so I gave them a system with no channels for testing.

I will figure out the best fix for this. Maybe I need tr revert that change and give t hem a tuner for the test system.

**Comment by jfabernathy** [comment]
This is not showstopper. More of a convenience

**Comment by bennettpeter** [comment]
This has been fixed. Manage recordings is in every page once again. No longer hidden, even if there are no channels.

**Comment by jfabernathy** [comment]
Is this version 466?  Will Android store push out a update?
