### ISSUE TITLE
Select live TV from program guide

### ISSUE THREAD

**Issue by iitywygms** [bennettpeter/android-MythTV-Leanfront#79]

**Comment by bennettpeter** [comment]
EPG already exists on leanfront.
Currently, LiveTV on leanfront does not create a recording for the show being watched.  It creates a recording called LiveTV for 1 hour and then watches it while it is recording.
Improvements that could be made:
- Record and watch from the program guide
- Create  a recording for the actual show being watched.
- Switch to the next show when the show is complete.
- Use the Program Guide to start a Live TV session.
- Provide a "record program" menu option that changes the recording type from Live TV to Recorded.

Which parts are important to you?

**Comment by iitywygms** [comment]
Thank you for reaching out I really appreciate it

My wish list is kind of simple.
I schedule all my recordings from mythweb.
So all that I would like is to be able to open the EPG, highlight a show
and click ok and have that show play until I press stop.

I use Kodi right now and it works.
But it's very heavy and I only use it to watch live TV.
Your contribution is lightweight, clean and works very well. If I could
easily select live TV shows then I would be in heaven.
And honestly, if you would like to open some sort of way to allow
contributions to your work I'd be happy to do so. Thank you.

**Comment by bennettpeter** [comment]
Live TV is rewritten to include this support in 7290bc2 . Released in 495
