### ISSUE TITLE
Too many recordings?

### ISSUE THREAD

**Issue by fe31nz** [bennettpeter/android-MythTV-Leanfront#80]
I have just bought a FireTV Stick 4K Max and installed leanfront on it.  When I tell it to connect to my mother's MythTV box, it works as expected.  When I change the address to my own MythTV box (mypvr.jsw.gen.nz, 10.0.2.4), it attempts to download data, but fails.  The likely cause is that I have >63000 recordings.  I have attached the file lfe.log which is the output of "adb logcat lfe:D *:S" from starting leanfront and clicking on "Refresh lists" to it crashing out back to the main FireTV menus.
[lfe.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/13808707/lfe.log)

**Comment by fe31nz** [comment]
I powered on the FireTV stick and ran leanfront.  It was still showing the data it downloaded from my mother's MythTV box when it connected to that.  So I went to the settings and checked that it was set to connect to my MythTV box, then did "Refresh Lists".  After a long time with little wheel circling, it finally crashed back to the main menu page.  Then I connected via adb and did "adb logcat".  The resulting file is attached.

[full_logcat_2024-01-16_21-58.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/13947893/full_logcat_2024-01-16_21-58.log)

**Comment by bennettpeter** [comment]
Thank you for your help. 
That log did not show anything useful. You need to run the logcat while the error occurs.
Please start 
`adb logcat | tee android.log`
 before causing the error, leave it running until after the crash, then hit Control-C. It will likely be a big file.

**Comment by bennettpeter** [comment]
Alternatively, If you could send me a backup of your MythTV mysql database, then I can recreate the error here and figure out what causes it and how to fix it.

**Comment by bennettpeter** [comment]
I created a database with 60,000 recordings and started leanfront. It gets an out of memory error while parsing the output from /Dvr/GetRecordedList. The solution will be to get the data in pieces so that the entire multi-megabyte xml document does not have to be in storage at one time.

**Comment by bennettpeter** [comment]
Fixed in v0-481-g2f4a197-m1.2.1-2-gc3114cd837 . However it can take many minutes to load 60,000 recordings. I added a setting to limit the number of recordings and videos to a specified number of the most recent (default 10000). To see all 60000 you need to change that setting and then have patience to wait around 5 minutes while it loads the recordings.
