### ISSUE TITLE
Recording override

### ISSUE THREAD

**Issue by dheian** [bennettpeter/android-MythTV-Leanfront#81]
If I have a recording rule for a series but don't want to record an airing, say, due to a schedule conflict, in mythfrontend I'm able to select it and choose "don't record this showing" or something similarly worded.

Unless I'm missing it, I can't seem to find a way in leanfront's upcoming recordings list to select to not record just that airing.

Thanks.

**Comment by bennettpeter** [comment]
I have implemented this and it will be in the next release, which will be available in a few days.
