### ISSUE TITLE
Incompatible IP Addresses

### ISSUE THREAD

**Issue by bennettpeter** [bennettpeter/android-MythTV-Leanfront#85]
Notify the user if the ip address entered into leanfront settings does not match the master ip address on MythTV Settings.

When they are different, recording lists and playback do not work correctly. Recordings do not show screenshots and banners and recordings cannot play.

**Comment by Jpilk** [comment]
This probably deserves the earlier label...

I have several installations of MythTV master, a SONY Android  TV and a FireTVstick 4k.  Most of the Mythboxes have connected immediately to leanfront but some have given a 'not connected to backend' display.  

That goes away on installation of openssh-server.  I haven't noticed that requirement in the docs  :-)

**Comment by bennettpeter** [comment]
I don't believe that installing openssh-server has anything to do with leanfront or MythTV. leanfront does not use ssh. Perhaps installing openssh-server disables some firewall that was preventing connection.

**Comment by bennettpeter** [comment]
I am reluctant to change the IP address handling. The inconsistency I have observed with having different values in leanfront and in mythbackend occurs only when the IP address in mythbackend is not accessible from leanfront. This can happen if your backend has multiple ip addresses, which should not be a common occurrence, or if you have localhost as your ip address in mythbackend.
