### ISSUE TITLE
release date drop down not working correctly

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#88]
Found this issue while trying to debug issue #87.

In the Videos tab, if I select a video with no release date and try to manually update, The drop box on date does not allow scrolling within the box.  The first pop up is a current calendar but I need to change the year. If I select  the 10 year range so I can get to 2012, if doesn't always show the complete set of those 10 years.  If I can some how manage to get to 2012, I can only see the first 3 months and then I can't scroll without the popup disappearing. I can't just type in the correct date

**Comment by bennettpeter** [comment]
This is not a leanfront issue. This is a web app issue. Please open it in the MythTV/mythtv repository.

**Comment by jfabernathy** [comment]
Sorry about that. will do.
