### ISSUE TITLE
recording playback exiting back to menu unexpectedly

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#89]
This issue didn't exist on the FireTV version of Leanfront before I started using the Amazon Store versions.

I watch the morning network news delayed.  What I do is start up Leanfront about 30-45 minutes after the recording has started.  This means that nothing out of the ordinary happens until I get to what was the "end" of the recording as it was when I started watching. Up until that point I can do the 1 minute skips using the right arrow to bypass commercials.  In the past, I could get within 1 minute of the current recording position and it would no longer advance as expected. So you are basically Live TV at that point.

However, since the move to the app stores, I've noticed that sometimes Leanfront will exit back to the menu when you get near the what it thinks is the end on a currently recording program. This is not an every time kind of issue. I'm currently on version: v0-470

I know you'll need the output of some adb command.  I need to know how to go about providing this.  Do I need to always start adb  before any playback of the news?  Or can I just wait for a failure and then dump something with adb?? I would also need the specific syntax of the adb command you need me to run.

**Comment by bennettpeter** [comment]
Probably an exception is occurring. To debug that will require a full log, and to start the adb logcat before it happens, not necessarily before you start watching, but before the error happens.

adb logcat | tee android.log

Unfortunately this may get very large if it runs for some time.

**Comment by jfabernathy** [comment]
This may take some days to get the log as it happens a good bit but not everyday.  Today it happened before I could get the adb going on another PC.

**Comment by bennettpeter** [comment]
I think I know what is happening. There is an intermittent exception if you try to skip forward when it is at the end of a recording. I am looking into that.

**Comment by jfabernathy** [comment]
Okay, I captured the log while running Leanfront prior to it exiting with the exception.  The time it exited was around 2/7/2024 at ~ 12:22PM
[android.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/14197552/android.log)

**Comment by bennettpeter** [comment]
This confirms what I thought. You are experiencing this exception. ( at 12:22:13.273)
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
I have a fix for it that I will test for a day or two and then if all is OK I will release it.

**Comment by bennettpeter** [comment]
Fixed in release v0-481-g2f4a197-m1.2.1-2-gc3114cd837
