### ISSUE TITLE
sound mutes briefly 5 seconds after restart from skip

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#9]
I recently noticed with the last few updates that after play starts from beginning, bookmark, or skip forward the sound works immediately but  briefly mutes 5 seconds later.
version v0-239-g7770891
Nvidia Shield TV  software version 8.2.1

**Comment by bennettpeter** [comment]
This is intentional. Some recordings have audio out of sync at the beginning of play or after a skip, and this brief interruption ensures the audio is synced.

**Comment by jfabernathy** [comment]
thanks, now that I understand, it's really not a  problem, but wondered if it was a indicator of some other issue underneath.
