### ISSUE TITLE
Videos category disappeared?

### ISSUE THREAD

**Issue by jfabernathy** [bennettpeter/android-MythTV-Leanfront#90]
I'm using v0-481 from Amazon store on a FireTV 4K Max.

I normally have on the left categories listed.  This morning I see Recently Viewed, All, Default, LiveTV, Tools.

Videos is missing.  If I check with mythfrontend on any FIreTV or PC, I see the videos category. Refresh list doesn't fix it or rebooting the FireTV does fix it. 

It used to work fine.  It also shows correctly on Kodi 20

Maybe a setting got changed accidentally?

**Comment by jfabernathy** [comment]
If I have the setting checked for Merging Recordings with Videos then Clicking on Refresh runs fast.  If I uncheck that setting, the Refresh Lists takes forever. I see an exception in the log ./adb logcat lfe:D *:s | tee android2.log

[android2.log](https://github.com/bennettpeter/android-MythTV-Leanfront/files/14281133/android2.log)

**Comment by jfabernathy** [comment]
Today I got an update on my backend to v34.0+fixes.202402141910.b6aabcbbf3~ubuntu22.04.1.

Now Leanfront shows the Video category as it used to.  Not sure why, but it is fixed

**Comment by bennettpeter** [comment]
That exception is in the new code you requested for sorting the videos by season and episode within title. It happened when it ht a video with no title. I will make a change to handle that error.

**Comment by jfabernathy** [comment]
The update seems to fix the issue for me

**Comment by bennettpeter** [comment]
The fix has not yet been rekeased

**Comment by bennettpeter** [comment]
https://github.com/bennettpeter/android-MythTV-Leanfront/issues/92#issuecomment-1951388199

**Comment by bennettpeter** [comment]
Fix is now live in  v0-487-g6d06cf7-m1.2.1-2-gc3114cd837
