### ISSUE TITLE
Changing playback group speed breaks bookmark and last position

### ISSUE THREAD

**Issue by mkheironimus** [bennettpeter/android-MythTV-Leanfront#94]
I installed from the Amazon app store on a Fire TV Stick 4k Max and connected to my v34 backend. Recordings with the playback group speed set above or below 100 start at the beginning even when selecting playback from bookmark or last position. Changing the speed in the playback group back to 100 restores the correct behavior. It also works as expected if I leave the playback group at 100 and change the speed while a video is playing.

**Comment by bennettpeter** [comment]
Thank you for finding this.

I will get a fix into the next version. 

In the meantime you can avoid the problem by setting audio decode to ffmpeg. You will not lose any audio quality, the app switches to ffmpeg audio anyway when there is a speed other than 100%.

**Comment by bennettpeter** [comment]
There is another problem. When you do a speed change, the first key press, from 100% to 110% closes the seek bar and you have to o into it again to make further changes. This is also solved by setting audio to ffmpeg.

**Comment by mkheironimus** [comment]
I do see that same problem, and also confirm that forcing ffmpeg audio resolves both.

I also just hit a problem where changing the speed from 100 during playback jumped back to the start. I feel confident that I did that before, but I wasn't very systematic in my testing (plus the fire stick is a new toy so I've been playing with a lot of settings). Using ffmpeg audio fixes that too, so I assume it's the same problem bubbling up in another place.

**Comment by bennettpeter** [comment]
Fixed in 2024/03/02 . Released in 495.
