### ISSUE TITLE
Request-DVD capability for Leanfront

### ISSUE THREAD

**Issue by krisbee** [bennettpeter/android-MythTV-Leanfront#95]
I would love for Leanfront to be able to navigate/play DVD Video_TS files and .iso files.  Currently I can use Leanfront for all my local viewing needs except those, which I have to use Kodi for on my FireTV.  I would love the ability to just do it all in Leanfront.

**Comment by mikestanczyk** [comment]
I would also like the ability to play. Iso files and perhaps .mkv files as well.  @krisbee how do you get the .iso files to the kodi firestick?  A network share like samba, or a nas?

**Comment by krisbee** [comment]
On Tue, Apr 23, 2024, at 9:40 PM, mikestanczyk wrote:
> 
> 
> I would also like the ability to play. Iso files and perhaps .mkv files as well. @krisbee <https://github.com/krisbee> how do you get the .iso files to the kodi firestick? A network share like samba, or a nas?
> 

Correct - a samba share.

**Comment by bennettpeter** [comment]
I recommend converting your DVDs to mkv files and adding those to the MythTV backend videos storage group. That way you can play them with leanfront. This is what I do with DVDs I want to watch. If you need to know the details of how to do this I can help you.

 If you already have mkv files, all you need to do is add them to the Videos storage group in MythTV. 

I do not have any plans to support reading ISO files or to support reading any files over SAMBA or NFS.

**Comment by mikestanczyk** [comment]
do you want to continue to help me here on Github or over private email?  either is fine by me.  i couldn't find your email via github.

**Comment by bennettpeter** [comment]
You can email me peterbenn1 at gmail.com

**Comment by bennettpeter** [comment]
If you need further help please feel free to email me. From my email account it looks like I may have neglected to respond to your last email in April. If that is the case I apologize.

**Comment by mikestanczyk** [comment]
No problem! I found a workaround.
Mike
